// packages/core/tests/plot-pipeline.test.js — PP-2a oracle. Pins the ported vpype pipeline (#core/plot) against a
// GOLDEN captured from the ORIGINAL penplotter for the SAME input: the optimize output + BYTE-EXACT DDCS gcode.
// This proves the DDCS profile-factoring preserved behavior on the wire. Plus a buildZip smoke. Auto-discovered
// by scripts/run-tests.js (packages/core/tests/).
import { optimize, renderGcode, buildZip, DDCS } from '#core/plot/index.js';

(async () => {
  const assert = (c, m) => { if (!c) throw new Error(m || 'Assertion failed'); };

  // The SAME known input used to capture the golden from the original penplotter.
  const polylines = [
    [[0, 0], [10, 0], [10, 10]],
    [[10, 10], [20, 10]],
    [[50, 50], [60, 50], [60, 60]],
  ];
  const settings = { penUpZ: 5, penDownZ: -1, drawFeed: 1500, zFeed: 500, docH: 200, flipY: true };

  // 1. optimize — golden: linemerge joined strokes 1+2 (shared endpoint 10,10); sort ordered; simplify kept all.
  const GOLDEN_OPT = '[[[0,0],[10,0],[10,10],[20,10]],[[50,50],[60,50],[60,60]]]';
  const opt = optimize(polylines, { mergeTol: 0.05, simplifyTol: 0.1 });
  assert(JSON.stringify(opt) === GOLDEN_OPT, 'optimize output != golden: ' + JSON.stringify(opt));

  // 2. renderGcode — BYTE-EXACT DDCS gcode captured from the original (proves the profile factoring changed no bytes).
  const GOLDEN_GCODE = `(--- DDCS pen plotter program ---)
(Generated by pen plotter app)
G21 (mm)
G90 (absolute)
G17 (XY plane)
G94 (feed per min)
G1 Z5.000 F500 (pen up to safe Z)
G0 X0.000 Y200.000 (rapid to stroke start)
G1 Z-1.000 F500 (pen down)
G1 X10.000 Y200.000 F1500
G1 X10.000 Y190.000 F1500
G1 X20.000 Y190.000 F1500
G1 Z5.000 F500 (pen up)
G0 X50.000 Y150.000 (rapid to stroke start)
G1 Z-1.000 F500 (pen down)
G1 X60.000 Y150.000 F1500
G1 X60.000 Y140.000 F1500
G1 Z5.000 F500 (pen up)
G1 Z5.000 F500 (final pen up)
M30
`;
  const gcode = renderGcode(opt, settings);
  assert(gcode === GOLDEN_GCODE, 'gcode NOT byte-exact.\n--- got ---\n' + gcode + '\n--- want ---\n' + GOLDEN_GCODE);
  assert(gcode.length === 511, 'gcode length ' + gcode.length + ' != 511');

  // 3. the DDCS machine profile is a DECLARED object (injection-ready for PP-4).
  assert(DDCS && DDCS.id === 'ddcs' && typeof DDCS.header === 'function' && typeof DDCS.footer === 'function',
    'DDCS profile declared with header/footer');

  // 4. buildZip smoke — entries -> a nonzero zip Blob larger than the raw content.
  const zip = buildZip([{ name: 'plot.gcode', content: gcode }]);
  assert(zip && typeof zip.size === 'number' && zip.size > gcode.length, 'buildZip nonzero zip: ' + (zip && zip.size));

  console.log('plot-pipeline (PP-2a) tests passed ✅');
})().catch((e) => { console.error('plot-pipeline tests failed ❌', e); process.exit(1); });
