// packages/core/plot/gcode/profiles.js — DECLARED machine profile(s) for the G-code emitter (PP-2a).
// renderGcode reads a profile (default DDCS). ONE profile today: the DDCS Expert M350 dialect the original
// penplotter hardcoded. This is INTEGRATION.md's "machine profile" registry SHAPE — a 2nd controller would be a
// 2nd entry + a selector. Rule of three: declare the shape now, DEFER the selector/engine until a real 2nd
// machine appears. The data stays a DECLARATION so PP-4 can inject a different profile without touching the emitter.
//
// A profile supplies the machine-specific STRINGS only; render/header/footer/path keep the file structure (the
// \n join conventions) so the emitted bytes are IDENTICAL to the pre-factoring emitter.

export const DDCS = {
  id: "ddcs",
  name: "DDCS Expert M350",
  // Program header (mm / absolute / XY plane / feed-per-min), then lift the pen to safe Z. Matches the Fusion
  // DDCS post: parens comments, no G10/G28.
  header: ({ penUpZ, zFeed }) => [
    "(--- DDCS pen plotter program ---)",
    "(Generated by pen plotter app)",
    "G21 (mm)",
    "G90 (absolute)",
    "G17 (XY plane)",
    "G94 (feed per min)",
    `G1 Z${penUpZ.toFixed(3)} F${zFeed} (pen up to safe Z)`,
  ],
  // Final pen lift + M30 program end (the trailing "" supplies the closing newline when joined).
  footer: ({ penUpZ, zFeed }) => [
    `G1 Z${penUpZ.toFixed(3)} F${zFeed} (final pen up)`,
    "M30",
    "",
  ],
  // Per-stroke blocks. DDCS M350 always emits X & Y (no modal axis suppression — matches the Fusion post's forceXYZ).
  rapidTo: (x, y) => `G0 X${x.toFixed(3)} Y${y.toFixed(3)} (rapid to stroke start)`,
  penDown: ({ penDownZ, zFeed }) => `G1 Z${penDownZ.toFixed(3)} F${zFeed} (pen down)`,
  drawTo: (x, y, { drawFeed }) => `G1 X${x.toFixed(3)} Y${y.toFixed(3)} F${drawFeed}`,
  penUp: ({ penUpZ, zFeed }) => `G1 Z${penUpZ.toFixed(3)} F${zFeed} (pen up)`,
};
